# Generated by Django 3.2.9 on 2021-12-02 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=20)),
                ('callerSource', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('policeStation', models.CharField(max_length=20)),
                ('circle', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('eventtype', models.CharField(max_length=100)),
                ('eventsubtype', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['city', 'policeStation', 'datetime'],
            },
        ),
    ]
